version: "3.7"
services:
  db:
    image: "postgres:15.2"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
      - "./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
    container_name: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 100